
### Criar o cliente
POST http://localhost:3003/users/createClient
Content-Type: application/json

{
    "name":"Lucas",
    "email":"lucas@lucas.com",
    "password":"123456",
    "cpf":"111.111.111.11"
}

### Login
# @name login
GET http://localhost:3003/users/login
Content-Type: application/json

{

    "email":"lucas@lucas.com",
    "password":"123456"

}

### Criar forma de pagamentto
POST http://localhost:3003/users/createPayment
Authorization: {{login.response.body.result}}
Content-Type: application/json

{
    "clientId": "123456789",
    "amount": 3000,
    "type":"credit card",
    "cardHolderName":"Lucas",
    "cardNumber":"4916 6705 5586 8558",
    "cardExpirationDate":"08/2022",
    "cardCvv": "560"
}

### Buscar pagamento
GET http://localhost:3003/users/getPayment
Authorization: {{login.response.body.result}}
Content-Type: application/json

{
    "id":"a78359b9-dd1e-47e1-8e46-c2fc3790b91d"
}